steps:
- bash: |-
    TAG=`git describe --tags --abbrev=0`

    if [ "$?" -eq 0 ]
    then
      echo "Found tag $TAG"
      git log --format=format:"- %s" --no-merges $TAG..HEAD > $(Build.ArtifactStagingDirectory)/changes.log
    else
      git log --format=format:"- %s" --no-merges > $(Build.ArtifactStagingDirectory)/changes.log
    fi

    echo $'\n\nEmoji legend available at https://gitmoji.dev' >> $(Build.ArtifactStagingDirectory)/changes.log
  displayName: Set changelog from git history
