parameters:
- name: useCache
  type: boolean
  default: true
- name: sdkVersion
  default: 5.x
  type: string
- name: updateAssemblyInfo
  type: boolean
  default: false
- name: assemblyInfoPath
  type: string
  default: $(Build.SourcesDirectory)
- name: assemblyInfoArtifactName
  type: string
  default: AssemblyInfo
- name: configuration
  type: string
  default: $(BuildConfiguration)
- name: buildArgs
  type: string
  default: ''
- name: coverageDirectory
  type: string
  default: $(build.artifactStagingDirectory)/coverage/.
- name: sonarHost
  type: string
  default: https://sonarcloud.io
- name: sonarProject
  type: string
  default: $(SONAR_PROJECT)
- name: sonarOrganization
  type: string
  default: $(sonarOrganization)
- name: sonarApiKey
  type: string
  default: $(sonarApiKey)
- name: sonarOnPullRequests
  type: boolean
  default: true
- name: sonarPullRequestProvider
  type: string
  values:
    - github
    - vsts
    - bitbucketcloud
  default: github
- name: githubApiKey
  type: string
  default: $(GitHubApiKey)
- name: coverageTool
  default: cobertura
  type: string
  values:
  - cobertura
  - jacoco
- name: summaryFile
  type: string
  default: '$(build.artifactStagingDirectory)/coverage/coverage.cobertura.xml'
- name: coverageArtifactName
  type: string
  default: $(Build.Repository.Name)-$(Build.BuildNumber)-coverage
- name: testOnWindows
  type: boolean
  default: false
- name: testOnLinux
  type: boolean
  default: false
- name: testOnMac
  type: boolean
  default: false
- name: coverageOnWindows
  type: boolean
  default: false
- name: coverageOnLinux
  type: boolean
  default: false
- name: coverageOnMac
  type: boolean
  default: false
- name: sonarOnWindows
  type: boolean
  default: false
- name: sonarOnLinux
  type: boolean
  default: false
- name: sonarOnMac
  type: boolean
  default: false
- name: codecovOnWindows
  type: boolean
  default: false
- name: codecovOnLinux
  type: boolean
  default: false
- name: codecovOnMac
  type: boolean
  default: false
- name: coverallsOnWindows
  type: boolean
  default: false
- name: coverallsOnLinux
  type: boolean
  default: false
- name: coverallsOnMac
  type: boolean
  default: false

stages:
- stage: Test
  displayName: Run tests
  dependsOn: Version
  jobs:
  - ${{ if parameters.testOnLinux }}:
    - template: ../../jobs/dotnet/01. test.yml
      parameters:
        image: linux-latest
        useCache: ${{ parameters.useCache }}
        sdkVersion: ${{ parameters.sdkVersion }}
        updateAssemblyInfo: ${{ parameters.updateAssemblyInfo }}
        assemblyInfoPath: ${{ parameters.assemblyInfoPath }}
        assemblyInfoArtifactName: ${{ parameters.assemblyInfoArtifactName }}
        configuration: ${{ parameters.configuration }}
        buildArgs: ${{ parameters.buildArgs }}
        publishCoverage: ${{ parameters.coverageOnLinux }}
        coverageDirectory: ${{ parameters.coverageDirectory }}
        sonarAnalysis: ${{ parameters.sonarOnLinux }}
        sonarHost: ${{ parameters.sonarHost }}
        sonarProject: ${{ parameters.sonarProject }}
        sonarOrganization: ${{ parameters.sonarOrganization }}
        sonarApiKey: ${{ parameters.sonarApiKey }}
        sonarOnPullRequests: ${{ parameters.sonarOnPullRequests }}
        sonarPullRequestProvider: ${{ parameters.sonarPullRequestProvider }}
        githubApiKey: ${{ parameters.githubApiKey }}
        coverageTool: ${{ parameters.coverageTool }}
        summaryFile: ${{ parameters.summaryFile }}
        coverageArtifactName: ${{ parameters.coverageArtifactName }}
        uploadCodeCov: ${{ parameters.codecovOnLinux }}
        uploadCoveralls: ${{ parameters.coverallsOnLinux }}
  - ${{ if parameters.testOnWindows }}:
      - template: ../../jobs/dotnet/01. test.yml
        parameters:
          image: windows-latest
          useCache: ${{ parameters.useCache }}
          sdkVersion: ${{ parameters.sdkVersion }}
          updateAssemblyInfo: ${{ parameters.updateAssemblyInfo }}
          assemblyInfoPath: ${{ parameters.assemblyInfoPath }}
          assemblyInfoArtifactName: ${{ parameters.assemblyInfoArtifactName }}
          configuration: ${{ parameters.configuration }}
          buildArgs: ${{ parameters.buildArgs }}
          publishCoverage: ${{ parameters.coverageOnWindows }}
          coverageDirectory: ${{ parameters.coverageDirectory }}
          sonarAnalysis: ${{ parameters.sonarOnWindows }}
          coverageTool: ${{ parameters.coverageTool }}
          summaryFile: ${{ parameters.summaryFile }}
          coverageArtifactName: ${{ parameters.coverageArtifactName }}
          uploadCodeCov: ${{ parameters.codecovOnWindows }}
          uploadCoveralls: ${{ parameters.coverallsOnWindows }}
  - ${{ if parameters.testOnMac }}:
      - template: ../../jobs/dotnet/01. test.yml
        parameters:
          image: macOS-latest
          useCache: ${{ parameters.useCache }}
          sdkVersion: ${{ parameters.sdkVersion }}
          updateAssemblyInfo: ${{ parameters.updateAssemblyInfo }}
          assemblyInfoPath: ${{ parameters.assemblyInfoPath }}
          assemblyInfoArtifactName: ${{ parameters.assemblyInfoArtifactName }}
          configuration: ${{ parameters.configuration }}
          buildArgs: ${{ parameters.buildArgs }}
          publishCoverage: ${{ parameters.coverageOnMac }}
          coverageDirectory: ${{ parameters.coverageDirectory }}
          sonarAnalysis: ${{ parameters.sonarOnMac }}
          coverageTool: ${{ parameters.coverageTool }}
          summaryFile: ${{ parameters.summaryFile }}
          coverageArtifactName: ${{ parameters.coverageArtifactName }}
          uploadCodeCov: ${{ parameters.codecovOnMac }}
          uploadCoveralls: ${{ parameters.coverallsOnMac }}

