parameters:
- name: packagesToPush
  type: string
  default: '*.nupkg'
- name: artifact
  type: string
  default: nuget
- name: environmentPullRequest
  type: string
  default: 'kritikos-io'
- name: feedNamePullRequest
  type: string
  default: Kritikos
- name: environmentRelease
  type: string
  default: 'kritikos-io'
- name: feedNameRelease
  type: string
  default: Kritikos

stages:
- stage: Deploy
  displayName: Deploys nugets
  dependsOn:
    - Build
    - Test
  jobs:
  - ${{ if ne(variables['Build.Reason'], 'PullRequest') }}:
      - template: ../../jobs/dotnet/02. nuget-deploy.yml
        parameters:
          artifact: ${{ parameters.artifact }}
          packagesToPush: $(Pipeline.Workspace)/${{ parameters.artifact }}/${{ parameters.packagesToPush }}
          environment: ${{ parameters.environmentPullRequest }}
          feedName: ${{ parameters.feedNamePullRequest }}
  - ${{ if eq(variables['Build.Reason'], 'PullRequest')}}:
      - template: ../../jobs/dotnet/02. nuget-deploy.yml
        parameters:
          artifact: ${{ parameters.artifact }}
          packagesToPush: $(Pipeline.Workspace)/${{ parameters.artifact }}/${{ parameters.packagesToPush }}
          environment: ${{ parameters.environmentRelease }}
          feedName: ${{ parameters.feedNameRelease }}

