parameters:
- name: packagesToPush
  type: string
  default: '*.nupkg'
- name: artifact
  type: string
  default: nuget
- name: environmentPullRequest
  type: string
  default: 'kritikos-io'
- name: jobNamePullRequest
  type: string
  default: kritikos-io
- name: feedNamePullRequest
  type: string
  default: Kritikos
- name: environmentRelease
  type: string
  default: 'kritikos-io'
- name: jobNameRelease
  type: string
  default: kritikos-io
- name: feedNameRelease
  type: string
  default: Kritikos

stages:
- stage: Deploy
  displayName: Deploys nugets
  dependsOn:
    - Build
    - Test
  jobs:
  - ${{ if and(ne(variables['Build.Reason'], 'PullRequest'),or(eq(variables['Build.SourceBranchName'], 'master'),eq(variables['Build.SourceBranchName'], 'main'))) }}:
      - template: ../../jobs/dotnet/02. nuget-deploy.yml
        parameters:
          artifact: ${{ parameters.artifact }}
          packagesToPush: $(Pipeline.Workspace)/${{ parameters.artifact }}/${{ parameters.packagesToPush }}
          environment: ${{ parameters.environmentRelease }}
          jobName: ${{ parameters.jobNameRelease }}
          feedName: ${{ parameters.feedNameRelease }}
  - ${{ if or(eq(variables['Build.Reason'], 'PullRequest'),or(eq(variables['Build.SourceBranchName'], 'master'),eq(variables['Build.SourceBranchName'], 'main')))}}:
      - template: ../../jobs/dotnet/02. nuget-deploy.yml
        parameters:
          artifact: ${{ parameters.artifact }}
          packagesToPush: $(Pipeline.Workspace)/${{ parameters.artifact }}/${{ parameters.packagesToPush }}
          environment: ${{ parameters.environmentPullRequest }}
          jobName: ${{ parameters.jobNamePullRequest }}
          feedName: ${{ parameters.feedNamePullRequest }}
  - job:
    displayName: Empty Job for compatibility

